### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by aylive** [aailabkaist/DiffRS#2]
Thanks for sharing your impressive work! I guess in the guide for rejection sampling, you mean,
-  "Download `DG/checkpoints/discriminator/cifar_uncond/discriminator_60.pt` at DG (https://drive.google.com/drive/folders/1Mf3F1yGfWT8bO0_iOBX-PWG3O-OLROE2).

**Comment by byeonghu-na** [comment]
Thank you for the notification. In the current version (https://github.com/aailabkaist/DiffRS/commit/13da74cc9ba43cd3037e9eba76fcbb0d07a4541c), I included your comment and updated the links directly. Thank you again for your interest.
